name: 'objects-filter'
description: 'Github Action Utility to filtering and mapping object'
author: 'vcnc-hex'
branding:
  icon: 'award'
  color: 'green'

inputs:
  json: # change this
    required: true
    description: 'JSON format of the Array type. ex) json: toJSON([...matrix...])'
  filter: # change this
    required: true
    description: 'Filter function body with input argument. ex) filter: return input.name'

runs:
  using: 'node12'
  main: 'dist/index.js'
