name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled, closed]
  push:
    branches:
      - main
      - 'releases/*'
jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Store matrix
        id: save
        uses: nickofthyme/object-remap@v1
        with:
          include.*.name: ${{ toJSON(github.event.pull_request.labels.*.name) }}

      - uses: ./
        id: test
        with:
          input: ${{ toJSON(fromJSON(steps.save.outputs.json).include) }}
          filter: label => label.name.startsWith('do')

      - name: Get output
        run: |
          echo ${{ steps.test.outputs.json }}
